delta_robot:     
  gazebo_ros_control:
    pid_gains:
      link_0_JOINT_1:
        p: 1
      link_0_JOINT_2:
        p: 1
      link_0_JOINT_3:
        p: 1

gazebo_ros_control:
    pid_gains:
      link_0_JOINT_1:
        p: 1
      link_0_JOINT_2:
        p: 2
      link_0_JOINT_3:
        p: 3